### PR TITLE
Fixes for #77 and #80

### PR DESCRIPTION
**Pull request by mrecachinas**
Double check it, but I've updated the Emacs instructions as per the anonymous feedback you got. I also did some housekeeping to ensure the tutorial is up to date.

### CODE REVIEW

**Comment by mrecachinas** [comment]
Also added a fix for #80

**Comment by mrecachinas** [comment]
The latest commit addresses #86

**Comment by mrecachinas** [comment]
Feel free to reject ebe493b. I simply ran make, but I noticed the generated HTML was not "prettified".

**Comment by aaronbloomfield** [comment]
I'd like to pull this into the (newly created) fall-2015 branch.  One option is to re-do the pull request into that branch; another is that I can pull it in once the semester ends.

**Pull request closed without merging**
