### PR TITLE
Master

### PR DESCRIPTION
**Pull request by AgentE382**
Fix printf issue from lecture. Editor automatically removed extraneous whitespace.

### CODE REVIEW

**Comment by AgentE382** [comment]
Someone else made a cleaner request.

**Comment by aaronbloomfield** [comment]
Thanks, though!  I'm assuming you used atom to edit the files, correct?

**Comment by AgentE382** [comment]
I did. I don't use it for coursework, but I usually use it for GitHub related stuff, since it integrates nicely. I use Sublime Text 3 for practically everything else.

**Comment by aaronbloomfield** [comment]
That would be why.  Atom (and, apparently, sublime) cut off all trailing spaces in HTML documents.  But when the HTML has embedded markdown, as these slides do, that can mess up the formatting.  In particular, there needs to be two spaces after each of the table of contents slide's lines (lines 74-80) in order for it to format correctly.

**Pull request closed without merging**
